class ALLIANCE_ERROR:
    DEFAULT_ERROR = 0
    ALREADY_AT_WAR = 1
    REQUEST_ALREADY_SENT = 1
    NAME_ALREADY_TAKEN = 4
    ALLIANCE_IS_FULL = 6
    ALLIANCE_DO_NOT_EXIST = 8
    ALLIANCE_IS_FLOODED = 25
    IS_AT_WAR = 32


class LOCK_ERROR:
    USER_ONLINE = 1
    USER_UNDER_ATTACK = 2
    USER_HAS_SHIELD = 3
    USER_TUTORIAL_NOT_COMPLETED = 6
